### ISSUE TITLE
Please add a home page

### ISSUE THREAD

**Issue by pcav** [gis-support/DIVI-QGIS-Plugin#1]
This repo would be ok.

**Comment by pcav** [comment]
The current one is in a Slavic language I do not understand well (and most other users as well).
Could you please add a translation?
All the best.

**Comment by p0cisk** [comment]
pb_tool script doesn't add i18n folder to zip package. I've uploaded new version 1.0.1 with translation, please check if English translation is now displayed correctly

**Comment by pcav** [comment]
Thanks. However, I'm referring to: https://divi.io/

**Comment by p0cisk** [comment]
Ah, I see. On the upper right corner of site is a switch between EN/PL language.

**Comment by pcav** [comment]
Thanks. Perhaps you could show the page according to the language of the browser?

**Comment by gis-support** [comment]
Well, it should works like that:) we will improve it asap.
1 maj 2016 19:23 "Paolo Cavallini" notifications@github.com napisał(a):
